# Generated by Django 2.1.3 on 2018-11-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0002_auto_20181114_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='name',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='alternative',
            name='operative_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='interest_type',
            field=models.CharField(choices=[('p', 'period'), ('e', 'effective'), ('n', 'nominal')], default='nominal', max_length=10),
        ),
    ]
