# Generated by Django 2.1.3 on 2018-11-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0003_auto_20181121_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('capitalizations', models.PositiveIntegerField(default=0)),
                ('efective', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('periodic', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
