# Generated by Django 2.1.3 on 2018-11-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0005_auto_20181122_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
