# Generated by Django 2.1.3 on 2018-11-26 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0005_auto_20181121_2137'),
        ('Calculator', '0010_auto_20181123_0435'),
    ]

    operations = [
    ]
