# Generated by Django 2.1.3 on 2018-11-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0011_merge_20181126_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.DecimalField(decimal_places=2, max_digits=9)),
                ('present_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('future_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.AlterField(
            model_name='interest',
            name='capitalizations',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='efective',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='interest',
            name='nominal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='interest',
            name='periodic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
    ]
